---
- name: Install Terra GPG Key
  ansible.builtin.dnf:
    name: >-
      https://repos.fyralabs.com/terra{{ ansible_facts['distribution_version'] }}/terra-gpg-keys-0:{{
      ansible_facts['distribution_version'] }}-4.noarch.rpm
    disable_gpg_check: true
  when: use_terra_repository

- name: Install Terra Repository
  ansible.builtin.yum_repository:
    name: terra
    description: terra $releasever
    metalink: https://tetsudou.fyralabs.com/metalink?repo=terra$releasever&arch=$basearch
    enabled: true
    gpgcheck: true
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-terra$releasever
  when: use_terra_repository
