[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "go"
auto-format = true
formatter = {command = "goimports"}
language-servers = ["gopls"]

[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log",  "serve"]

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true
gofumpt = true
