format = """\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$golang\
$character"""

add_newline = false

[directory]
style = "bright-black"

[character]
success_symbol = "[▶](bold green)"
error_symbol = "[▶](red)"

[git_branch]
format = "[($branch )]($style)"
style = "cyan"

[git_status]
format = "[($ahead_behind )]($style)"
up_to_date = "✓"
style = "blue"

[cmd_duration]
format = "[($duration )]($style)"
style = "yellow"

[python]
symbol = "py "
format = "[$symbol($virtualenv )]($style)"
style = "green"

[golang]
symbol = "go "
format = "[$symbol($version )]($style)"
version_format = 'v${raw}'
style = "blue bold"